### ISSUE TITLE
Can we use refs with archer elements

### ISSUE THREAD

**Issue by RajeevSebastian** [pierpo/react-archer#103]
My application requires me to draw arrows from the source to the target step by step like generating a graph one step at a time. I thought of using refs on the archer element component and changing the relations attribute on the fly. But when I use Ref for the archer element it ends up being null. 
I can get the ref to the archer container. and there is a sourcetoTargetMap in the state property. Can I use that or need to use something else?

I am new to React and do not know the react way.
Any help would be appreciated?

Thanks for this library ... It is pretty good and easy to understand and use
Maybe an example showing how to use it dynamically will make it easier for new users :)

**Comment by RajeevSebastian** [comment]
![image](https://user-images.githubusercontent.com/54682134/83357426-0e74b800-a321-11ea-85b3-63e0bb3eece2.png)

**Comment by pierpo** [comment]
Hello, can you give a visual example of what you want? It can be hand-drawn, whatever. That'll help in assisting you :blush: 
Thanks!

**Comment by RajeevSebastian** [comment]
Sure
![waitforgraph](https://user-images.githubusercontent.com/54682134/83358606-98288380-a329-11ea-9a90-5c6463eac1b8.png)

**Comment by RajeevSebastian** [comment]
In each step, I want to draw an arrow as shown.
Each <td> is an archer element
Hope this helps :)

**Comment by pierpo** [comment]
Thanks! That's way clearer :wink: 

I don't think you need any refs for that. This looks like a classic usage of `react-archer`, nothing exotic :wink: 

Your whole table should be wrapped with `ArcherContainer`. Then each cell should be wrapped with `ArcherElement`. Each of these elements should then handle their relations to one-another by referencing their ids.

But I don't see why you'd need refs :thinking: 

If you can share a snippet of code I'd be able to help you more :blush:

**Comment by RajeevSebastian** [comment]
Yeah sure. Bear in mind the table is created based on user input.
this is the table body
`let tablebody = schedule.map((element, index) => {
      const columns = [];
      for (var i = 1; i <= numTransactions; i++) {
        if (i == element.transaction) {
          schedule[index].ref = React.createRef();
          const column = (
            <ArcherElement
              id={
                element.transaction +
                element.action +
                (element.dataitem ? element.dataitem : '')
              }
            >
              <td ref={schedule[index].ref}>
                {' '}
                {element.action + (element.dataitem ? element.dataitem : '')}
              </td>
            </ArcherElement>
          );`

this is the table component (react-bootstrap)
const table = (
      <>
        <Table
          striped
          bordered
          hover
          responsive
          variant="dark"
          style={{ marginTop: '15px', textAlign: 'center' }}
        >
          <thead>
            <tr>{transactionArray}</tr>
          </thead>
          <tbody>
            {tablebody.map((element) => {
              return <tr>{element}</tr>;
            })}
          </tbody>
        </Table>
      </>
    );
`<ArcherContainer noCurves ref={archerRef}>
                <div>{table}</div>
              </ArcherContainer>`

**Comment by pierpo** [comment]
Thanks :wink: 

I'm still not 100% clear on this.

Why don't you add the `relations` props to your ArcherElement? What information are you missing?

I mean something like this:

```jsx
            <ArcherElement
              id={
                element.transaction +
                element.action +
                (element.dataitem ? element.dataitem : '')
              }
              relations={[{
                targetId: transaction2 + action2 + dataitem2, // I don't know the logic here but it should point to the other element ID you want
                targetAnchor: 'top',
                sourceAnchor: 'bottom',
              }]}
            >
              <td ref={schedule[index].ref}>
                {' '}
                {element.action + (element.dataitem ? element.dataitem : '')}
              </td>
            </ArcherElement>
```

**Comment by pierpo** [comment]
Since you said you're not very familiar and you said this:

> I thought of using refs on the archer element component and changing the relations attribute on the fly.

Allow me to say that you might want to use the internal state of your React Component to store your info
https://reactjs.org/docs/state-and-lifecycle.html

Does that help?

**Comment by RajeevSebastian** [comment]
Sorry I did not mention this before. I am trying to make it interactive. So the user clicks a button and the next arrow is created. Won't your code generate all the  arrows in one go ?

**Comment by pierpo** [comment]
In that case you should have something like this. Replace `this.state.transactions[123]` with the logic that is relevant to know whether your transaction exists.

```jsx
const relationForCurrentElement = this.state.transactions[123] ? [{
                targetId: transaction2 + action2 + dataitem2, // I don't know the logic here but it should point to the other ArcherElement's id you are aiming
                targetAnchor: 'top',
                sourceAnchor: 'bottom',
              }]
  : [];

           <ArcherElement
              id={
                element.transaction +
                element.action +
                (element.dataitem ? element.dataitem : '')
              }
              relations={relationForCurrentElement}
            >
              <td ref={schedule[index].ref}>
                {' '}
                {element.action + (element.dataitem ? element.dataitem : '')}
              </td>
            </ArcherElement>
```

**Comment by pierpo** [comment]
I'm sorry it's quite hard to help because this is very tied to the logic you want to implement :wink: 
But I am pretty sure you don't need refs and you should use your component's state.

**Comment by RajeevSebastian** [comment]
Hey no problem I agree that it is hard to look into the issue without having the code.
So correct me If I am wrong but essentially what you are suggesting is re-render the entire table component each time the button is clicked to generate the next arrow right?
Once again thank you for your prompt replies :)

**Comment by pierpo** [comment]
> So correct me If I am wrong but essentially what you are suggesting is re-render the entire table component each time the button is clicked to generate the next arrow right?

Yes indeed, changing the state will re-render everything in your component!
But unless you have a big table, that shouldn't be a performance issue.
If it is an issue, then you'll have to tinker things to re-render only the stuff you need (cut down in more components, do some optimizations to not re-render them... there are many things that can be done).

But it will still look like what I'm suggesting, and there won't be refs, trust me :wink: 

> Once again thank you for your prompt replies :)

My pleasure :blush:

**Comment by RajeevSebastian** [comment]
Yeah, re-rendering will work fine in my case. So if I were to work on a large table how would I optimize it. 
If you can just point me to some resources online it would be of immense help :) just for future use-cases.

**Comment by pierpo** [comment]
What kind of resources are you looking for? React in general?
I think the official documentation is really good for that purpose :blush:

**Comment by RajeevSebastian** [comment]
Hey Pierre.
I did follow the procedure to re-render the table component.
If I hardcode the values then the arrows are generated. However, using arrays to represent relations does not work for some reason...
If you have the time can you see the code 
[https://gist.github.com/RajeevSebastian/f1b4c7bd4ef5ecdb42dd1ee0c7efc687](url)

**Comment by pierpo** [comment]
Hey,
I tried to run your code but I can't get it to run properly. I have an input that adds nothing.

Could you run it on https://codesandbox.io/ ?

How deep have you been in debugging? Try to use the react inspector https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en to look at your components and their props. You should compare your `ArcherElement` ids and relations.


Some feedbacks on your code. I haven't read it all there are probably many other things.

- the file is very big, you should split it down. Do multiple components (one for the form, one for the table, one for the graph). You should also take out the constants like the color list to another file so that yours is shorter.
- do not confuse state and props! I see that you have `this.state.props`. I don't know what led you to have a `props` key in your state but it might indicate that you're confused about those.
- your code is quite complex, I'm a little lost. One thing I would advise you to do is avoid mutations. `map`, `filter`, `reduce` will be your friends to manipulate arrays.
> About mutations. I haven't full read it but it looks fine https://medium.com/@fknussel/arrays-objects-and-mutations-6b23348b54aa
> About map/filter/reduce https://medium.com/@joomiguelcunha/learn-map-filter-and-reduce-in-javascript-ea59009593c4
