### ISSUE TITLE
pointer events are missing

### ISSUE THREAD

**Issue by uniqalien** [pierpo/react-archer#105]
Hi! 

There is an issue with pointer events for content of ArcherElement component.
Mouse actions or interactions with component content are not working at all. 
Adding z-index of -1  to svg overlay solves the issue. But anyway its not more than workaround. 
Relevant for latest version. This issue appears after upgrade to latest. Doesnt have it on 1.5.0 version. 

Thanks.

**Comment by pierpo** [comment]
Hi!

Thank you for reporting the issue. I'll have a look when I'll have some time.

Thanks!

**Comment by viztor** [comment]
@pierpo @uniqalien 
I also ran into the same issue.
Add `pointer-events: 'none'` to SVG container would smoothly solve this issue, I will submit a PR later.

**Comment by larissa-n** [comment]
Thanks for looking into this, @pierpo. Here's a button inside <ArcherContainer /> that is not clickable: https://codesandbox.io/s/popout-diagram-react-archer-q8y3z

Is the SVG that's created by <ArcherContainer /> in front of its content (maybe blocking it)?

**Comment by pierpo** [comment]
Hi @larissa-n ! Sorry I did not see your answer.

Actually @viztor was right. You need to add `svgContainerStyle={{ pointerEvents: 'none' }}` to your `ArcherContainer`.

@viztor did a PR that was released in 3.0 to have this behaviour by default :blush:
