### ISSUE TITLE
Can't build react-archer using `npm run build`

### ISSUE THREAD

**Issue by MosheZemah** [pierpo/react-archer#112]
Hi, seems like I can't build (or run npm install successfully) since I get errors on TypeScript code.
Shouldn't webpack config use a ts-loader or something? Didn't see any of that in the webpack.prod.config.js file.
Can someone help me running the build please?

**Comment by jfo84** [comment]
This isn't a TypeScript project. It uses Facebook's flow types

**Comment by pierpo** [comment]
I don't understand, could you provide the output of your build command?
