### ISSUE TITLE
Arrows can't render properly when the start point and end point have the same x or y

### ISSUE THREAD

**Issue by viztor** [pierpo/react-archer#113]
![1F05C8BE-F485-4a3b-B036-1A50118AED6D.png](https://user-images.githubusercontent.com/3511050/93285703-19882100-f808-11ea-9735-63fdaebb2fbe.png)
 there should ideally be a way to specify an offset so the line can render properly

**Comment by viztor** [comment]
same issue as #109

**Comment by pierpo** [comment]
Yes indeed, thank you for referencing the proper issue yourself :blush:
