### ISSUE TITLE
Arrow get reversed if the related elements are close vertically

### ISSUE THREAD

**Issue by ElMahdiEz** [pierpo/react-archer#115]
Hi, first thank you for this useful library.

My problem is that the arrow getting reversed between two vertically close elements as it is shown in this figure : 

![Capture1](https://user-images.githubusercontent.com/57039119/94076427-f60b3a80-fdf4-11ea-8a7f-c06bca11b2f1.PNG)

But it's displayed correctly for non close elements as in this figure :

![Capture2](https://user-images.githubusercontent.com/57039119/94076502-2a7ef680-fdf5-11ea-96be-b13de8ebb9db.PNG)

I would like to have the arrow stars from the right side of Root element and ends on the left side of Element3 like it is for the Element4.

Here you can find the code : 
https://codesandbox.io/s/keen-frost-qqk41

Thank you !

**Comment by kamalkavin** [comment]
Facing the same problem
<img width="426" alt="arrow-issue" src="https://user-images.githubusercontent.com/54261321/94135086-95c1da80-fe80-11ea-892e-e03d8cd69dfa.png">

relations={[
{targetAnchor:'left',																												sourceAnchor:'left'}
]}

**Comment by ElMahdiEz** [comment]
Hi @kamalkavin,
Did you find a solution bro ?

**Comment by ElMahdiEz** [comment]
@pierpo

**Comment by kamalkavin** [comment]
> Hi @kamalkavin,
> Did you find a solution bro ?

not yet bro

**Comment by pierpo** [comment]
Hi!

Thanks for reporting this 😉 
Actually, this is the same as this issue: https://github.com/pierpo/react-archer/issues/69

I don't have any simple solution yet 😬 
The drawing logic needs some rework!

No ETA yet, I don't really have a recommendation to solve your issue. I'd change the layout to use `bottom` to `top` in your case... I hope it's an option for you!

**Comment by ElMahdiEz** [comment]
Okay we can use it until we find a solution

**Comment by pierpo** [comment]
Perfect. I'll close this issue since it's a duplicate.
Thank you for your patience :blush:
