### ISSUE TITLE
refreshScreen not working

### ISSUE THREAD

**Issue by katrinamsnyder** [pierpo/react-archer#125]
Using version 3.0.0, calling the refreshScreen from my ref on ArcherContainer is not having any effect.

package-lock:
    "react-archer": {
      "version": "3.0.0",
      "resolved": "https://awn-gpojnkmp1.na.ad.whirlpool.com:501/react-archer/-/react-archer-3.0.0.tgz",
      "integrity": "sha512-+Uc6VyljE+nTWVproEELn1Tlv7MowXMNK7BAc4loji2+U3nTcw3neaAm8xnsNyYxByDjmsjxBR/6Z7/lfBHVig==",
      "requires": {
        "react-fast-compare": "^2.0.4",
        "resize-observer-polyfill": "1.5.0"
      }
    }

ref:   const arrowContainerRef = React.useRef<ArcherContainer>(null);
passing ref: <ArcherContainer strokeColor={theme.palette.text.primary} strokeWidth={1} ref={arrowContainerRef}>
calling refreshScreen: arrowContainerRef.current.refreshScreen();

To test, a button click is calling refreshScreen, but the arrow is still not being redrawn:
![image](https://user-images.githubusercontent.com/11785824/99825636-4963e580-2b25-11eb-9fe5-7125db039714.png)

Please let me know if I'm missing something.

**Comment by pierpo** [comment]
Hi,

It feels like the problem does not come from `refreshScreen`. It looks like the shape is correct, but the svg viewport is somehow clipped.

If `refreshScreen` wasn't working, the shape of the path wouldn't look like it's going to the proper place.

- Can you double check your CSS?
- Would you be able to provide a reproducing example?

**Comment by katrinamsnyder** [comment]
Hi,

I was hoping the refreshScreen would force re-render the arrows, using what is currently scrolled into screen, but it's sounding like I misunderstood. The content is all inside a Material UI Card component. The arrows draw correctly initially, but when the overflow X is triggered, once I scroll over as you can see the other components render fine, but not the arrow. 

I'll try to play more with my css to see if I can fix it. Unfortunately my code is through github Enterprise and proprietary per company policy, or else I'd be happy to share.

Thanks for your response.

**Comment by AntoineGlacet** [comment]
Hey I am having the same issue with material UI flex containers confusing archer, did you find a solution?

**Comment by jacopobacci** [comment]
Hello, I managed to solve the problem by setting the width of the container based on the width of the children where `ArcherElement`s are expanding dynamically.

```
  useLayoutEffect(() => {
    if (
      childRef.current?.scrollWidth &&
      parentRef.current?.clientWidth &&
      childRef.current?.scrollWidth > parentRef.current?.clientWidth
    )
      setWidth(`${childRef.current?.scrollWidth}px`);
  }, [childRef, expanded, parentRef, setWidth]);
  ```
  
  ```
    ...
    const parentRef = useRef<HTMLDivElement>(null);
    const childRef = useRef<HTMLDivElement>(null);
    const [width, setWidth] = useState("100%");
    ...
      <div ref={parentRef} style={{ width }}>
      <ArcherContainer strokeColor="red" endMarker={false}>
        <div className="flex" ref={childRef}>
          {items?.map((item) => (
            <MyNode site={item} key={item.id} parentRef={parentRef} childRef={childRef} setWidth={setWidth} />
          ))}
        </div>
      </ArcherContainer>
    </div>
    ```
    
Like that the width increases and scrolling right the branches are shown correctly.
