### ISSUE TITLE
Can't require 0.2.3

### ISSUE THREAD

**Issue by jakobdamjensen** [pierpo/react-archer#13]
Thanks for making this repo. I wanted to try it out but ran into an issue using 0.2.3.

For some reason, I can't require version 0.2.3. I've checked the diffs and I can't figure out what happened since 0.2.2 that would have broken it.

> yarn init
> yarn add react-archer@0.2.3
> node
> require("react-archer")
Error: Cannot find module 'react-archer'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)

0.2.2 works fine

> yarn init
> yarn add react-archer@0.2.2
> node
> require("react-archer")
{ ArcherElement: [Getter], ArcherContainer: [Getter] }

Do you have any idea what is going on?

**Comment by jakobdamjensen** [comment]
OK so it seems like the `lib` folder is gone but it is still referenced as 

> "main": "lib/react-archer.js",
> "module": "lib/react-archer.js",

in `package.json`

**Comment by pierpo** [comment]
Oops. So sorry about that 😨 
I'll fix it in 0.3.0 that I'll release tomorrow.

Thanks for your feedback!

**Comment by geoff-va** [comment]
Not sure if related to the current issue, I'm unable to import `react-archer` in 0.2.3. It appears it's looking for it in the current directory:

```shell
./src/components/MyFile.js
Module not found: Can't resolve 'react-archer' in '/usr/src/app/src/components'
```

**Comment by pierpo** [comment]
@geoff-va Yes, has to be related 😅 

I just released 0.3.0, you can try again!

**Comment by jakobdamjensen** [comment]
Yeah it seems to work now! Thanks

**Comment by pierpo** [comment]
Cool! Enjoy 😊
