### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by RdNetwork** [pierpo/react-archer#136]
Hello!

I wanted to use this package but it seems that it doesn't support React 17 despite its October 2020 release. I think it should not bring breaking changes since apparently this was a rather thin release.

Do you plan on updating the package soon to reflect that?

Thanks in advance!

Remy

**Comment by pierpo** [comment]
Hello!

Yes definitely, that would be safe.
Is it blocking for you or is it just raising a warning? Since it's a peerDependency it should simply be a warning, right?

I'll handle it for the next release (should happen soon)!

**Comment by RdNetwork** [comment]
Here's what I get when trying to install archer through npm:

![image](https://user-images.githubusercontent.com/4118704/115517197-2d58a180-a287-11eb-8e37-4626dff8eb43.png)

Not sure how that fits in your question, but I tend to avoid force-installs, for safety and based on my still faint knowledge of Node/NPM.

**Comment by oskari** [comment]
Probably fixed by changing the react-archer peerdependencies to `"react": "^16.9.0 || ^17"` in https://github.com/pierpo/react-archer/blob/master/package.json#L36  and updating packages. It should be fairly simple, you could leave a PR about it

**Comment by pierpo** [comment]
Yes indeed, I'll publish this in the coming days :blush: (along with your changes @oskari !)

**Comment by pierpo** [comment]
Should be good with `v3.1.0` :blush:
