### ISSUE TITLE
Arrows unattaching after drag and drop - but only half the time

### ISSUE THREAD

**Issue by seastan** [pierpo/react-archer#138]
I've run into a strange bug with this library when used in conjunction with `react-beautiful-dnd`. When I move a `Draggable` to a new `Droppable`, the arrows connected to that `Draggable` come unattached and point to `0,0`. But after I move the `Draggable` again (to another `Droppable`), the arrows return. So on and so forth. This behavior was not present when I was experimenting with other arrow libraries, such as `react-simple-arrows`, so I am raising the issue here.

![](https://i.imgur.com/S4gb0C6.gif)

Anyone have an idea what's going on here? This is the best svg arrow library I've found for react, and I'd really like to use it, so in order to facilitate a solution or workaround I've made a CodeSandbox that demonstrates the problem:

https://codesandbox.io/s/vertical-list-with-multiple-drop-targets-forked-4sq6f

**Comment by pierpo** [comment]
Hi!

Thank you for the feedback! And thank you for the Code Sandbox, this is going to be very helpful.

This needs investigation indeed! I can tell you that we're going through a piece of code that states `return Point(0, 0)` in case a ref is not found. I guess this could happen because the children elements are mounted/unmounted, but are not detected properly by the DOM watcher in place (`resize-observer-polyfill`).

If you want to investigate it yourself, I'd love the help 😉  I won't have time to give it a look myself for now, unfortunately.

As a dirty workaround, you could refresh the arrows upon release by calling the ref method `refreshScreen()` on your container once you release the element. It's super dirty but it might work!

**Comment by seastan** [comment]
@pierpo Thanks for the response!

I should mention that I'm a beginner at react. I've tried looking to it it as much as I can, but hit a wall with this. I am not familiar of the intricacies of the mounting and unmounting of child elements.

I'm also not sure exactly how to call a ref method of ArcherContainer. If it's just a couple lines, would you be able to add them to the CodeSandbox and see if they do the trick? After the release of the element, `onDragEnd` gets called, so I'm guessing it should go at the end of that?

**Comment by pierpo** [comment]
I tried to add the `refreshScreen()` workaround on your code sandbox and it doesn't work, unfortunately.

It needs further investigation, then. I can't give you an ETA for now since I am quite busy these times 😢

**Comment by seastan** [comment]
No worries, thanks for giving it a try!

**Comment by dimapx** [comment]
@pierpo Has there been any progress with this issue? We're suffering from a similar use case where we unmount and then mount an element and the arrows won't refresh properly (`refreshScreen` doesn't help).

@seastan Were you able to find a work around?

**Comment by seastan** [comment]
@dimapx No, I ended up going with `react-simple-arrows`, but if this were patched I would definitely switch back, as there were some other features of this library that I liked.

**Comment by pierpo** [comment]
@dimapx No solution yet :pensive: 

I just had another look. I just updated the codesandbox, the provided one was not working: https://codesandbox.io/s/9mpg9

Well, I still wonder what's going on. It looks like when the element changes columns, `react-archer` loses track of it. When it only changes rows, it works properly.

I guess (really a rough guess) this is related to how the element is moved from one column to another on `react-beautiful-dnd`. Somehow, the refs are not properly tracked and handled on `react-archer`'s side.

It will need further investigation...

**Comment by pierpo** [comment]
Good news! Solved by 4.0.1 :blush:
