### ISSUE TITLE
Property `noCurves` does not exist on type

### ISSUE THREAD

**Issue by albingroen** [pierpo/react-archer#145]
# Issue

The `noCurves` property does not (accordingly to Typescript) exist on the `ArcherContainer` component, but it seems to have the effect it's supposed to have. So the solution should just be to update the interface.

```
Property 'noCurves' does not exist on type
```

![CleanShot 2021-05-19 at 10 36 23](https://user-images.githubusercontent.com/19674362/118782149-14dfa500-b88e-11eb-8320-c5995c3f0f7b.png)

**Comment by pierpo** [comment]
Hey! Thanks for the issue. It was missing indeed. I just published a new version with the fix :wink: 
Thanks!
