### ISSUE TITLE
Collapsing div around the elements

### ISSUE THREAD

**Issue by robinvenneman** [pierpo/react-archer#15]
Tested this library inside a container with draggable elements and it seems that the `ArcherContainer` element adds a div with the ref `storeParent` around the child elements, right after the SVG. Because this collapses its height up to the position of the lowest element it's not really useful for this use case, I fixed it by adding the same styles as the `svgContainerStyle`, notably 100% height & width...
Would it be possible to update this CSS or allow passing a custom style prop to adjust this? 
Not even sure if there needs to be a separate div element to render the child elements.
I can submit a PR if you want.

**Comment by AlisonWonderlandApps** [comment]
I'm also facing a similar issue. Also, not sure if anyone has ever dockerised their app and tried to deplo it but the arrows go very strange

**Comment by pierpo** [comment]
Sorry I didn't have a look at this issue.
I'm not sure I understand the problem, can you give a simple example? (small implem + screenshot)

**Comment by robinvenneman** [comment]
Yeah I fixed that locally for this use case I had but seemed like I broke something else in the default example so will revisit and see if I can open a PR.

**Comment by robinvenneman** [comment]
![screenshot 2018-12-07 at 22 08 26](https://user-images.githubusercontent.com/1286347/49672823-a8311100-fa6c-11e8-959c-de0bfc4ab4c3.png)

So this screenshot shows the default example with 2 background colors, one for the main `div` returning from `ArcherContainer` and another from the `div` that contains the children that are passed to it. I can set a `style` prop with width & height but can't really control the other div through props so maybe I can use some CSS with `> div` selector or similar, but maybe it would be better to set this to `height: "100%"` by default. Another solution is maybe to use a [`React.fragment`](https://reactjs.org/docs/fragments.html) around the children and then there is no additional div.

this example shows just setting the nested div to 100% height. 
![screenshot 2018-12-07 at 22 12 19](https://user-images.githubusercontent.com/1286347/49672972-33aaa200-fa6d-11e8-895c-10218c38986f.png)

**Comment by robinvenneman** [comment]
Easiest way to fix this is https://github.com/pierpo/react-archer/pull/26

I also tried with a `React.Fragment` but since it has a ref `storeParent` that is used to calculate the coordinates and such it should probably stay, unless the top-level `div` could be used instead but I haven't tried that.
