### ISSUE TITLE
Suggest: Render order of paths

### ISSUE THREAD

**Issue by levi2ki** [pierpo/react-archer#160]
Hi, i'd like to suggest feature - render order of paths.
For example, when we want to highlight some path in one-to-many relation, order of rendering path is not configurable and we cann't move highlighted path to top:
![image](https://user-images.githubusercontent.com/25363699/138602852-620140bf-bfa6-45ba-9387-a4ab44554756.png)
Introducing order property to relation can help in moving some paths to top:
![image](https://user-images.githubusercontent.com/25363699/138602920-5c80e32e-1355-4e22-bcc0-f00d643911f5.png)
```jsx
{
   targetId: 'root',
   targetAnchor: 'right',
   sourceAnchor: 'left',
   label: 'Arrow 3',
   order: 1,
   style: {
     strokeColor: '#54ff11',
   },
}
```
**TBD**: global or local to relations array order???

**Comment by pierpo** [comment]
Hey, sorry I never answered to the issue! (only the PR)

It makes sense that this would be local to each relations array. I don't see how this could be global :blush:
