### ISSUE TITLE
Unregister elements

### ISSUE THREAD

**Issue by robinvenneman** [pierpo/react-archer#17]
To unregister transitions when an ArcherElement unmounts, it should delete all the svg's with both `to` and `from` this element. So this would be `unregisterAllTransitions` on the context. 

And also, the ref to the element is still there in the container state so the ArcherElement should also have `unregisterChild` and also call this on unmount.

What are your thoughts about this @pierpo ? I can submit a PR (working on it at the moment, seems to work for my use case,  dynamically adding and removing elements and drawing arrows between them, was sometimes using a temporary element for dragging with the same id & ref so needed to fix this).

**Comment by pierpo** [comment]
Sure, totally makes sense. A PR would be welcome of course 😊 
Thanks for your contributions it's really great to have your help! 🤗 

I'll check the PRs out when I'll have more time next week!

**Comment by pierpo** [comment]
@robinvenneman Thanks for your work, PR is merged!

I'll publish this ASAP 😊
