### ISSUE TITLE
Minified React error #321 in v4.0.0

### ISSUE THREAD

**Issue by ThiloAschebrock** [pierpo/react-archer#172]
There seems to be an issue with version 4.0.0 that can crash the parent React app:

**Error trace:**
> react-archer.js:2 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
>     at z (react-archer.js:2:1)
>     at useState (react-archer.js:2:1)
>     at react-archer.js:2:1
>     at renderWithHooks (react-dom.development.js:16305:1)
>     at updateForwardRef (react-dom.development.js:19226:1)
>     at beginWork (react-dom.development.js:21636:1)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
>     at invokeGuardedCallback (react-dom.development.js:4277:1)
>     at beginWork$1 (react-dom.development.js:27451:1)

Issue, cf. https://reactjs.org/docs/error-decoder.html?invariant=321
> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. **You might be breaking the Rules of Hooks** 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

This is probably related to https://github.com/pierpo/react-archer/pull/167. I can't pinpoint the error nor give a short example how to reproduce it.

**Comment by pierpo** [comment]
Uh-oh. I had a look at the code, I don't see any suspicious hook call. It's supposed to be an invalid `useState` but I don't see how.
Have you investigated the other reasons? (mismatching version, copies of React etc.)

**Comment by Thomas101** [comment]
Here's a sandbox that reproduces the error... https://codesandbox.io/s/gifted-sunset-r5zwrq?file=/src/index.js


react 18.0.0
react-dom 18.0.0
react-archer 4.0.4

```js
import { createRoot } from "react-dom/client";
import { ArcherContainer } from "react-archer";

const rootElement = document.getElementById("root");
const root = createRoot(rootElement);

root.render(
  <div>
    <ArcherContainer />
  </div>
);

```

**Comment by Thomas101** [comment]
@ThiloAschebrock you beat me to it with seconds to spare 🙈

**Comment by ThiloAschebrock** [comment]
> @ThiloAschebrock you beat me to it with seconds to spare see_no_evil

Oh no, how unlucky :) But your example is even more minimal, which is nice 👍🏻

**Comment by pierpo** [comment]
Amazing, many thanks to both of you! I need to investigate this asap!

**Comment by pierpo** [comment]
I think I got it. Looks like the devDependency version of `react` in `react-archer` gets included in the bundle.

https://github.com/pierpo/react-archer/blob/2258a2bbf4eb57b1fe9265f857b8e901e5940472/package.json#L80

So, two instances of React live side by side and it makes the hooks go crazy (as said in the docs).

I found a solution by adding React externals in the Webpack configuration, but somehow it still includes React if it is found in the `node_modules`.
I could try generate a build this way, but I'd like to understand _why_ it only works if React is completely removed from the devDependencies of `react-archer`...

```tsx 
  externals: {
    react: 'react',
    reactDOM: 'react-dom',
  },
```

I should probably question the presence of the `examples` directory in the repo which shares the same `package.json` as the lib...

**Comment by pierpo** [comment]
Looks like adding `skipLibCheck` to the build tsconfig solves the issue... I have no idea why. The lib uses babel to transpile Typescript, I didn't think `tsconfig.json` would have any impact on the final build.

```diff
+  "compilerOptions": {
+    "skipLibCheck": true
+  },
```

**Comment by pierpo** [comment]
I just released 4.0.1. The issue should be solved :blush: 

I'd love to hear from you if it's the case.

Sorry about the delay with this, I was on holiday last week!

**Comment by Thomas101** [comment]
I can confirm that 4.0.1 fixes it in my use case 👍 . Thank you & hope you had a good holiday

**Comment by ngocducdim** [comment]
Oh god thanks for the update

**Comment by ThiloAschebrock** [comment]
I can also confirm that it is working 👍🏻
