### ISSUE TITLE
In a Next.js app when you go to a page via a <Link /> click the lines don't load, but when you refresh the page the lines work

### ISSUE THREAD

**Issue by josephfarina** [pierpo/react-archer#184]
Hey! I was working on a project and noticed this bug and was wondering if you have seen it before? More than happy to look into it and open a PR up.

One thing to note is that I get tons of these errors below *both* when the arrows don't show up after accessing the page via a Next.js `<Link />` click and also when the arrows work accessing the page directly.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/17398284/204201902-e77652fc-ef92-4d71-88d3-abcdd91fa227.png">

**Comment by pierpo** [comment]
Hi!

I have absolutely no experience with Next, so I can't give a hint without looking 🙈 
Do you have a reproduction example ?

Thanks 😊

**Comment by louislefebvre** [comment]
I do experience the same using Remix framework. I think it might be related to server side rendering?
I am not sure to be honest, I tried any example from the examples folder and lines would not draw, and I would also get the same error as shown in the screenshot.

Thanks for the hard work by the way!

**Comment by pierpo** [comment]
I reproduced it with remix, thanks.

It broke with 4.2.0, you can use 4.1.0 for now!

I'll have a look 😉

**Comment by pierpo** [comment]
Oh well, this unpublished PR solves it https://github.com/pierpo/react-archer/pull/181 😄 

Publishing 4.2.1!

**Comment by pierpo** [comment]
4.2.1 published, problem should be solved 😊 

Thank you!

Please feel free to re-open if it's not.

**Comment by louislefebvre** [comment]
Thanks for the quick fix!

Lines are drawn, but there is now this following error output in Remix server console, as well as hydration errors in the browser console:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
```

On my side, this got fixed using this remix utility to use my component client side only: https://github.com/sergiodxa/remix-utils#clientonly
