### ISSUE TITLE
Updating relations prop

### ISSUE THREAD

**Issue by robinvenneman** [pierpo/react-archer#19]
I noticed that updating the `relations` prop doesn't actually trigger any updates in `componentWillReceiveProps` in the `ArcherElement` component because of the `relationsWithStringifiedLabels` equality check that uses the `label` on the relations... so not sure how exactly that should be fixed right now, I suppose it should just check if there is any relation added or removed and then run the appropriate update?

**Comment by AlisonWonderlandApps** [comment]
@robinvenneman & @pierpo  I'm having this same issue... did you have a workaround on forcing the arrows to re-render once they get a new relation? (code snippet would be great!)
My issue is that I have several different graphs to display in different tabs, but the arrows only render correctly for the FIRST display. 
I also cannot manually draw arrows between 2 nodes by adding a new relation to the graph once already rendered :(
Any suggestions or help would be appreciated!!!

**Comment by robinvenneman** [comment]
@AlisonWonderlandApps Yeah I've fixed dynamically adding / removing elements and adding or removing relations by updating the props... I will open a PR soon, just haven't completely figured out that `relationsWithStringifiedLabels` check yet.

**Comment by pierpo** [comment]
Thanks @robinvenneman for handling this.
I'll have to dive into this and think this through as well. Sorry about all these issues 😄 

As always, your PR is very welcome 😊

**Comment by pierpo** [comment]
So indeed there is a mistake in the `relationsWithStringifiedLabels`, it only compares labels right now (which was not intended).

But even fixing it raises another issue: when you change a relation from one arrow to point to another element, the previous relation is not removed.

I have a solution for this, I'll try to implement it asap!

**Comment by pierpo** [comment]
This PR https://github.com/pierpo/react-archer/pull/25 should solve it 😊

**Comment by pierpo** [comment]
Fix published, tell me if you still have issues 😉

**Comment by AlisonWonderlandApps** [comment]
awesome! Will check it out! Thanks both!

**Comment by robinvenneman** [comment]
Great job @pierpo thanks! A bit different from my solution but it works perfectly.
