### ISSUE TITLE
Random marker id is hard to test

### ISSUE THREAD

**Issue by jrfferreira** [pierpo/react-archer#23]
With version 0.3.0, the marker elements use a random key as id/key, but it became hard to test using snapshots. Does anyone have an approach to test it?

https://github.com/pierpo/react-archer/blob/5eb6b3a792b20b48a1acc3e5740cae6413eb9440/src/ArcherContainer.js#L287-L288

https://github.com/pierpo/react-archer/blob/5eb6b3a792b20b48a1acc3e5740cae6413eb9440/src/ArcherContainer.js#L105-L109

**Comment by pierpo** [comment]
Ah, indeed. Sorry, I did not think about this issue!

I should find another solution to get unique ids for each arrow.

Any suggestion welcome 😊

**Comment by robinvenneman** [comment]
Hmm @jrfferreira shouldn't you mock the `react-archer` dependency if you are unit testing another piece of code that implements this? If you are talking about testing `react-archer` itself then it can probably use a fixed value for the random generated it, e.g. by mocking `Math.random()` itself...

**Comment by jrfferreira** [comment]
Hi @robinvenneman, just for clarification, I'm using snapshots (with enzyme) to guarantee that the result of the implementation (SVG) will always be the same.

**Comment by pierpo** [comment]
Hi @jrfferreira!
I guess @robinvenneman's answer still makes sense. You can mock `Math.random()` in your snapshot tests so that it always returns the same value (or a value that is incremented at each function call so that arrow markers don't get a duplicate id).

Still, I'll try to come up with a better internal solution. Having random ids like that is not ideal.

**Comment by pierpo** [comment]
It feels like this is not really an issue, since solutions were provided. I said I'd improve the fact that there random IDs but actually I can't really find any downsides about this solution for now.

Closing, might reopen if needed!
