### ISSUE TITLE
multiple arrows, different colors

### ISSUE THREAD

**Issue by matiishyn** [pierpo/react-archer#33]
here's my expected result
![image](https://user-images.githubusercontent.com/3661065/50593695-13220c00-0ea2-11e9-9d90-70dba0a64391.png)
Trying to use this module to draw arrows
But cannot find a way to have different arrows with different colors (Black and Red in my case)
Is it possible?

**Comment by pierpo** [comment]
@matiishyn Hi! Yes it is 😊 
The documentation was not up to date.

You can add a `style` key to each relation.

```javascript
          <ArcherElement
            id="element2"
            relations={[
              {
                style: { strokeColor: 'blue', strokeWidth: 5 },
                targetId: 'element3',
                targetAnchor: 'left',
                sourceAnchor: 'right',
              },
            ]}
          >
            ...
          </ArcherElement>
```
