### ISSUE TITLE
Removing all elements in Example 2, removes everything in the page

### ISSUE THREAD

**Issue by edkotkas** [pierpo/react-archer#34]
Opened the example page, went on the example 2 tab. Started removing the elements, when just the root element is left it will allow it to be removed and this will cause the following error and the page goes blank..

![image](https://user-images.githubusercontent.com/9152439/50764804-cd7f8d80-126b-11e9-9274-1afb735a8a09.png)

**Comment by pierpo** [comment]
Woops, indeed. It's only the example that is wrong. Nothing critical then 😊 

I'll fix it. Thanks for reporting it 😉
