### ISSUE TITLE
Sometimes the arrowheads do not display

### ISSUE THREAD

**Issue by dcwills** [pierpo/react-archer#38]
I'm finding that arrowheads do not always display. the line is there, it just stops short. is this a known issue?

**Comment by pierpo** [comment]
Hi!

Well, it might be related to this https://github.com/pierpo/react-archer/issues/24
But I am not sure.

I would really appreciate if you could provide a piece of code to reliably reproduce it 😊

**Comment by dcwills** [comment]
I figured out the problem. It appears that things go awry by certain characters (space, unicode) in the id string, such as:
```
                                        <ArcherElement
                                            id="hello world"
                                        >
```
I tried to fix my code by switching to `targetId: encodeURI("hello world")`, but surprisingly enough, that didn't work.

**Comment by dcwills** [comment]
This fixes the problem in my code:
```
return encodeURI(str).replace(/%/g,'_');
```

**Comment by mrsauravsahu** [comment]
Experiencing the same issue, even the examples do not render arrowheads.
However, can't reproduce the error in v1.1.2. 
Tried checking the diff but couldn't notice anything obvious.

**Comment by pierpo** [comment]
It's weird that it happens on the examples... 🤔 
What browser do you use?

**Comment by mrsauravsahu** [comment]
Usually firefox, but tried on both Firefox and Chrome.

**Comment by ronandowlingcullen** [comment]
I had the same issue when using brackets "(" in my id, try removing/replacing the brackets (or other special characters). Slashes seem to work for me.

**Comment by pierpo** [comment]
I guess we should add an encoding in the id's then.

I guess I could add `return encodeURI(str).replace(/%/g,'_');` as suggested above but it doesn't feel completely robust (because 'abc%123' would become 'abc_123'... which is not really obvious for the end user).
One way that I see could be to do this, but it feels kinda hacky: `return encodeURI(str).replace(/_/g,'__').replace(/%/g,'_');`

**Comment by chandrakantap** [comment]
I also facing a similar issue, when using with react-router and the URL has the special character  `'`. This rendering the arrow svg with  marker-end prop as below:
`
<g>
   <path d="M40,46.5 C55,46.5 55,46.5 70,46.5" 
             marker-end="url(http://localhost:3000/flowchart-study'#arrow6374280400351586lpicon_daa3da12-e27d-40d0-b029-e4192a346590daa3da12-e27d-40d0-b029-e4192a346590)" 
            style="fill: none; stroke: blue; stroke-width: 2;">
  </path>
</g>
`

And arrow heads  are not showing.

<img width="466" alt="Screenshot 2020-09-18 at 8 33 59 PM" src="https://user-images.githubusercontent.com/50820059/93613311-544bae00-f9ee-11ea-9720-c4d2f2ff0991.png">

encoding the `targetId` does not encode the url part.

**Comment by katrinamsnyder** [comment]
Did one of the releases fix this issue? I also have a URL that has special characters in it, and can't find a way to control that part. I'm currently at version 3.0.0

**Comment by pierpo** [comment]
Hey!

I have looked into it. I think I will remove the hack that was made to fix the arrow markers on Safari. I don't see it anymore on recent versions of Safari, and removing this hack would solve your issue.

(the hack being to have the whole url instead of only the path without the domain)

**Comment by pierpo** [comment]
Fixed both issues (about time!) with release 4.1.0.

We now:
- encode the arrow ids so it's not necessary anymore to have URI-compatible characters
- do not use the whole URL to show the arrow markers (breaks older safari display but fixes it on all other browsers for apps that have special character in the url)

**Comment by katrinamsnyder** [comment]
Thanks for this!!!
Any chance you have a 3.x branch that you could PR that fix into and have a
3.3.1 release? Updating to React 18 will be pretty painful for me 😅
Katrina

**Comment by pierpo** [comment]
Have you tried upgrading to 4.1.0? It's supposed to still work with React < 18 :blush:

**Comment by katrinamsnyder** [comment]
Ah yes you’re right, sorry about that!

Thanks again! Much easier than trying to change my url handling 😅

Katrina

**Comment by pierpo** [comment]
Glad I could help :wink:
