### ISSUE TITLE
Arrows overlap the other elements.

### ISSUE THREAD

**Issue by sanuradhag** [pierpo/react-archer#45]
Is there a way to avoid the arrows from overlapping other elements.
![Screen Shot 2019-05-02 at 1 08 19 PM](https://user-images.githubusercontent.com/24251976/57061810-f1178980-6cdb-11e9-9827-e311c2b580fb.png)

I want to draw arrows arround the elements without overlapping other elements.

**Comment by pierpo** [comment]
Hello!

Do your elements have a background color? Because the arrows are supposed to be in a div behind your layout so it should already be the case 🤔 
Unless there's a bug 😉 

Can you confirm that these elements have a background color?

**Comment by sanuradhag** [comment]
Yes elements do have a background color.

**Comment by pierpo** [comment]
> Yes elements do have a background color. And becouse the arrows were behind the elements I had to set the z-index of the svg.

Well if you put the SVG in front it's normal that they're over all the elements 🤔 

So in the end you would expect arrows to be on top of some elements but behind others...?

**Comment by sanuradhag** [comment]
Yes. I want the arrows to be around the elements if the are going over the elements.

**Comment by pierpo** [comment]
Unfortunately this is not possible with the method that is used to draw the arrows. You can have a look at how the library works and think of a solution but nothing comes to my mind.

My recommendation, based on your problem:

- remove the `z-index` that you added and keep the white `background-color`
- try to have less overlap. For example, the arrow should go from top of element 1 to bottom of element 2, not right of element 2 to bottom of element 1. (with a little more space between elements to make the arrows visible)

I don't see any other solution, sorry 😬

**Comment by pierpo** [comment]
I'm closing the issue since there's no simple solution on the library's side.

Feel free to tell me if you can think of a simple feature that would help solving your problem.

**Comment by sanuradhag** [comment]
I woul like to implement this feature in your library. I'll create a pull request once I finish the feature.

**Comment by meoyawn** [comment]
@sanuradhag hey man, https://github.com/dagrejs/dagre has overlap avoidance, but you need to implement your own rendering
