### ISSUE TITLE
Differences on calculated SVG path on dev/production

### ISSUE THREAD

**Issue by danielr18** [pierpo/react-archer#47]
First of all, great library, thank you for the work @pierpo. I'm getting a weird error which reason I can't figure out. The elements are connected perfectly with the arrows during development, but when I build the app or the storybook where the component is used, the path is not the same, they seem to take a very long path instead of the shortest one.

### Development:
![image](https://user-images.githubusercontent.com/9046616/57198943-08a67a80-6f47-11e9-9951-86cb3430f01d.png)

### Production:
![image](https://user-images.githubusercontent.com/9046616/57198947-13610f80-6f47-11e9-96fd-b2255463034b.png)

![image](https://user-images.githubusercontent.com/9046616/57198995-d2b5c600-6f47-11e9-8d33-ed27c6867f62.png)

@pierpo Have you seen this happening before? If not, I can try to make a reproduction.

**Comment by pierpo** [comment]
Hi! Thank you for the kind words :blush: 
It's very likely to be related to this issue https://github.com/pierpo/react-archer/issues/24. Can you investigate it? The minification done by terser (used by webpack) is buggy and produces non equivalent code...

**Comment by danielr18** [comment]
It must be that issue, closing this one as it's a duplicate. Thanks!

**Comment by pierpo** [comment]
> It must be that issue, closing this one as it's a duplicate. Thanks!

Well, not 100% sure 😉 Your problem is not exactly the same so the cause could have been different.
Keep me updated, I hope you'll manage to fix it!

**Comment by jrfferreira** [comment]
I also have the same issue, and I'm still looking for a solution. Unfortunately, solutions on issue #24 do not help in my case.

**Comment by pierpo** [comment]
> I also have the same issue, and I'm still looking for a solution. Unfortunately, solutions on issue #24 do not help in my case.

Sorry that you also have an issue...
Would you happen to have a minimal reproducing example that you could share? I'd love to help but I'm completely in the blind for now.

**Comment by jfo84** [comment]
@jrfferreira Could you elaborate? There's an equivalent setup with Uglify to disable function inlining if that's the issue. The feature is essentially useless with modern JavaScript engines
