### ISSUE TITLE
Labels are not clickable when there are many paths present

### ISSUE THREAD

**Issue by hashwin** [pierpo/react-archer#50]
When there are > 4 paths, labels get stuck under the path on the right and become unclickable.

Code sandbox with reproduction:
https://codesandbox.io/s/magical-hypatia-hgyoc?fontsize=14

This is copied from example #2 with added click events.
As you can see, the label "3 hello" is unclickable.

**Comment by pierpo** [comment]
Indeed, I see what you mean (but the example is wrong, I guess there's a mistake in the link 😉)

I don't know how to solve this yet... 🤔 
It looks like the latest path in the DOM is shadowing the foreign objects of the other paths.

(everything underneath the selected path on the screen-shot is not reachable by clicks 
![image](https://user-images.githubusercontent.com/6313316/60843931-47bbab00-a1d8-11e9-8f01-87181dc988bf.png) )
