### ISSUE TITLE
Any way to allow right angled arrows rather than curved ones?

### ISSUE THREAD

**Issue by hashwin** [pierpo/react-archer#52]
I would like to achieve something like this:

![Blank](https://user-images.githubusercontent.com/406115/60958276-b6f1e600-a323-11e9-8ed4-76884436cf92.png)

Any way this is possible using archer?

**Comment by pierpo** [comment]
Hey @hashwin!

Not yet, unfortunately 😊 It's in the TODO but I've never done it.

`Options to customize the path shape more (straight line, right angle line, smoothed right angle path)`

PR welcomed 😉

**Comment by wirelessed** [comment]
Upvote for this feature - I have a complicated diagram and straight lines would definitely help!

**Comment by pierpo** [comment]
I just deployed `v1.3.0`. You may try it now :blush: 

https://github.com/pierpo/react-archer/pull/65

**Comment by wirelessed** [comment]
Hi! Thanks for the change! It works fine - however, is it possible for the lines to be direct diagonals from one point to another, instead of being L-shaped currently?

**Comment by pierpo** [comment]
Hi!

It's a good idea. It's not possible for now though, it is a different feature 😉 
I'll create a new issue for that.

No ETA yet!

Thanks!
