### ISSUE TITLE
Add z-index to svg

### ISSUE THREAD

**Issue by SevereOverfl0w** [pierpo/react-archer#53]
this would make it possible to ensure it's above the elements it is drawing arrows between.

**Comment by SevereOverfl0w** [comment]
When I did this, I also had to use `pointer-events: none;` in order to have pointer events (e.g. mouseover) pass straight through to my components.

**Comment by pierpo** [comment]
Hey! Can you provide more details? Do you want a props to set the z-index?

**Comment by SevereOverfl0w** [comment]
I'm not sure, I found that I needed to apply styles to the svg, but there wasn't a way to style it.

**Comment by mitchellwarr** [comment]
Im having the same problem. But just moving the svg to be drawn after the container content was enough to put the arrows on top

**Comment by mitchellwarr** [comment]
https://github.com/pierpo/react-archer/pull/85

**Comment by pierpo** [comment]
@mitchellwarr I encountered your issue and actually adding `z-index: -1` to the SVG container solves the issue, whereas moving the elements as you did doesn't.

Can you give me an example?

**Comment by pierpo** [comment]
@SevereOverfl0w @mitchellwarr BTW you can use the (yet) undocumented `svgContainerStyle` to add a `-1` z-index.

```jsx
<ArcherContainer className="container" strokeColor="red" svgContainerStyle={{ zIndex: -1 }}>
```
