### ISSUE TITLE
[Feature request] strokeStyle => dotted and dashed arrows

### ISSUE THREAD

**Issue by Spirarel** [pierpo/react-archer#59]
# Add ability to make lines dotted or dashed

I'm not sure how challenging this would be with your svg implementation, but it would be  a welcome addition!

**Comment by pierpo** [comment]
Indeed that's a good suggestion 😊
I need to look this up.

PR is welcomed, I'm not spending too much time on this project, unfortunately!

**Comment by Spirarel** [comment]
Looks like you're calling `path` to do the styling?
https://github.com/pierpo/react-archer/blob/8709513aa27ffa6043de2c29181fe2dc551abdf0/src/SvgArrow.js#L166-L170

I'm not sure it supports stroke styling. [SVG strokes do, however.](https://www.w3schools.com/graphics/svg_stroking.asp) Maybe there's something to glean from that implementation.

**Comment by pierpo** [comment]
@Spirarel Yes indeed, I think adding `strokeDasharray` as a prop would just do the job 😊

**Comment by pierpo** [comment]
I just released it with 1.2.0 :blush:

**Comment by Spirarel** [comment]
Hey, nice job! I'll try this tomorrow!

**Comment by Spirarel** [comment]
Working great! Thanks for adding this feature! Stars to you! =)

**Comment by pierpo** [comment]
Thank you for the relevant feature request 😊
