### ISSUE TITLE
Jest conflicts

### ISSUE THREAD

**Issue by kamilneczaj** [pierpo/react-archer#6]
I added your library to my project where I use Jest for testing, and since then I have the following error while running test in my project:
`TypeError: environment.teardown is not a function`
According to this an article at Stackoverflow [1] and my investigation the Jest version which is installed with `react-archer` conflicts with the version which is needed at my project. However `react-archer` should not depend on `jest` and `jest-environment-jsdom`, because the testing framework as well as `react-scrips` are dev dependencies.

Please move `react-scripts` which generates conflicting dependencies to `devDependencies`. This solves the problem for me.

[1] https://stackoverflow.com/questions/51809948/jest-with-typescript-typeerror-environment-teardown-is-not-a-function?noredirect=1&lq=1

**Comment by pierpo** [comment]
Thank you for your feedback. Sorry I didn't answer before, I didn't see your issue.
I'll have a look asap!

**Comment by pierpo** [comment]
[Should fix it](https://github.com/pierpo/react-archer/pull/8).

Sorry it took me so long. This is such a simple change!

**Comment by pierpo** [comment]
Closing since I don't have any news. The fix should work.

Please tell me if it doesn't 😊
