### ISSUE TITLE
Duplicate SVGs for programmatically added elements

### ISSUE THREAD

**Issue by sharkattackhq** [pierpo/react-archer#7]
This library is proving very useful to me, so thanks for building it! I'm having a problem where the SVGs are being duplicated when new elements are added to the DOM. I'm using react-dnd to drag an element onto a target. When that happens, a new object is added to an array in state, and the DOM updates accordingly. But when this happens, the existing SVGs are duplicated, as well as a new SVG being added. It's impossible to see visually, but it makes react throw lots of 'two children with the same key' errors. At the moment I can work around it by momentarily returning an empty div in render().

Is there a better way to trigger a redraw?

**Comment by pierpo** [comment]
Thank you for your issue report! (and for your kind words!)
Can you provide me a minimal example or maybe a chunk of code? I need to reproduce the issue to be able to work on it 😊

Thanks 😉

**Comment by yuriyhrytsyuk** [comment]
@sharkattackhq You can add key prop to <ArcherContainer> that will change after dragging new element to force a redraw.

**Comment by hadrienk** [comment]
@yuriyhrytsyuk @sharkattackhq yes, that fixed it for me as well. 

Great component!

**Comment by pierpo** [comment]
Should be fixed with the new release, thanks everyone! 😊

**Comment by AlisonWonderlandApps** [comment]
could you share how you achieved using these libraries together @pierpo @sharkattackhq @yuriyhrytsyuk ?? Having some trouble with integrating them :(

Some example code (where the render method is from the DropTarget and the BoxDemo is the DragSource

`    render() {
      return this.props.connectDropTarget(
        <div style={styles.container}>
          <ArcherContainer strokeColor="#6ebdc2">
            {Object.keys(this.state.boxes).map(key => {
              const { left, top, title, id, relations } = this.state.boxes[key];
              console.log("key", key, this.state.boxes[key], left);
              return (
                  <BoxDemo
                    style={{...styles.box, left, top}}
                    key={key}
                    left={left}
                    top={top}
                    id={id}
                    relations={relations}
                  >
                    {title}
                  </BoxDemo>
              );
            })}
          </ArcherContainer>
        </div>
      );
    }
}

export default DropTarget(ItemTypes.NODE, nodeTarget, collect)(GraphDrop);`

**Comment by pierpo** [comment]
@AlisonWonderlandApps Thanks for the kind words 😉 

I don't have the whole thing in your code, for example the state is missing so I can't know what's wrong.

Did you have a look at the two examples I put? I just deployed them on the Github page: https://pierpo.github.io/react-archer/
The code is under `example/` in this repo!

**Comment by AlisonWonderlandApps** [comment]
Hey @pierpo thanks for getting back to me... I can get the arrows to work per your example. But When I am trying to use the same with react-dnd, the arrows do not seem to draw for me

What state were you interested in ? 
The relations prop is in the following form:

```
const relations = [
  {
    from: { anchor: "bottom" },
    to: { anchor: "top", id: "element2" }
  },
  {
    from: {anchor: "bottom" },
    to: { anchor: "top", id: "element3"}
  },
  {
    from: {anchor: "bottom" },
    to: { anchor: "top", id: "element4"}
  }
];
```

**Comment by AlisonWonderlandApps** [comment]
ok nevermind! I have it somewhat working now! Thanyou for this great library @pierpo and if anyone runs into similar issues as i mentioned.. feel free to ping me :)

**Comment by pierpo** [comment]
@AlisonWonderlandApps Oh, glad you hear you found a solution.
Sorry I was not fast enough to help you 😉 

And thanks for the kind words 😄
