### ISSUE TITLE
Not working properly with Gatsby.js

### ISSUE THREAD

**Issue by junaid33** [pierpo/react-archer#71]
Hey, I'm trying to use react-archer on a Gatsby site. Locally, it is working perfectly. When I deploy it, the arrows don't know show and our svg traced images don't finish loading either. 

Example:
<img width="1395" alt="Screen Shot 2019-11-08 at 4 53 46 AM" src="https://user-images.githubusercontent.com/34615258/68467206-cb67c180-01e3-11ea-9afa-529dd3a0e2f4.png">

What could be the cause? It something going wrong during the build?

**Comment by pierpo** [comment]
Hey! Sorry I never answered.

Do you have a reproducible example? Thanks :blush:

**Comment by pierpo** [comment]
The fact that it's only in prod mode makes me think that it's related to this: https://github.com/pierpo/react-archer/issues/24

**Comment by pierpo** [comment]
Just tried with latest gatsby version, it works. Closing now.
