### ISSUE TITLE
Anchor location: middle

### ISSUE THREAD

**Issue by sho-87** [pierpo/react-archer#72]
Possible to add a new anchor location, which is directly to the middle of the source/target element?

Would it be as simple as adding an additional case to the switch in `ArcherContainer.js L55` (https://github.com/pierpo/react-archer/blob/master/src/ArcherContainer.js#L55)...

Something like `return rectToPoint(rect).add(new Point(rect.width / 2, rect.height / 2))`?

**Comment by pierpo** [comment]
Hey! Makes perfect sense indeed :blush: 

Would you like to do a PR? I could do it but it might take longer since I'm a little busy these times :wink:
