### ISSUE TITLE
Adding svg background overlays?

### ISSUE THREAD

**Issue by twigs67** [pierpo/react-archer#74]
Hello,

Is it currently possible to add svg background overlays? 

Thanks

**Comment by pierpo** [comment]
Hi @twigs67! Thanks for the issue.

What do you mean by background overlays? Do you have an example?
Can't you add `background-color` to the container?

Thanks!

**Comment by pierpo** [comment]
Hey @twigs67 !

Can you answer my questions above so that I can see how I can improve the lib?

Thanks 😉

**Comment by pierpo** [comment]
No answer for 2 years, I'll re-open if it's needed.
