### ISSUE TITLE
Feature request: reverse arrow style

### ISSUE THREAD

**Issue by jamesdbrock** [pierpo/react-archer#77]
Thanks for this library @pierpo , it's very nice.

The way element relations work, all relations to a source element must be known at the time the source element is rendered. Sometimes it would be programmatically convenient to express all relations to a target element instead of a source element. We could accomplish this by adding a single flag to the arrow style that indicates that instead of being drawn forward, with the arrowhead pointing at the target, the arrow should be draw backward, with the arrowhead pointing at the source.

```javascript
Style
{
  strokeColor: string,
  strokeWidth: number,
  strokeDasharray: number,
  arrowLength: number,
  arrowThickness: number,
  noCurves: boolean,
  arrowForward?: boolean    // New property. Defaults to True.
}
```
Then in [`generateAllArrowMarkers`](https://github.com/pierpo/react-archer/blob/c1f23183b8d1218d65496e3abc199a5aa1dd0f0c/src/ArcherContainer.js#L285) draw the arrowhead pointing at the source if the `arrowForward` property is `False`.

**Comment by pierpo** [comment]
It makes sense indeed. I'll have a look when I find some time!
Thank you for the suggestion :hugs: 

(sorry I took so long to answer, I guess I missed the notification!)

**Comment by viztor** [comment]
solution should be the same as #79

**Comment by mstykow** [comment]
Any update on this? This would be very nice to have: i just had to write a whole bunch of logic (useState, useEffect) in order to pass the children's ids back up to the parent component from whence arrows are drawn when a simple switch in direction would have been a one-liner.

**Comment by jfo84** [comment]
@mstykow This is not a particularly simple piece of work. You can always fork the library and put up a PR

**Comment by pierpo** [comment]
Should be solved by https://github.com/pierpo/react-archer/pull/139 😉
