### ISSUE TITLE
stroke opacity?

### ISSUE THREAD

**Issue by maayanalbert** [pierpo/react-archer#78]
Thanks for the awesome package @pierpo! Is there any way we can set the opacity of an `ArcherElement`? I know that strokes have a `stroke-opacity` css property but adding that to an `ArcherElement`'s `style` doesn't seem to do anything.

**Comment by maayanalbert** [comment]
Figured it out, I just ended up using `rgba(0, 0, 0, .5)` for the `strokeColor` property.

**Comment by pierpo** [comment]
Cool! Glad you figured a solution. :blush: 
Thanks for the issue.
