### ISSUE TITLE
Issue with remove elements in ArcherContainer

### ISSUE THREAD

**Issue by ilyaburmaka** [pierpo/react-archer#81]
Hey, if remove an element from the start of array I have this issue. If I remove from the end of the array - I don't have this problem. Maybe whoever has an idea of how to fix it
I use version 1.5
React 16.8
```
  <ArcherContainer noCurves={true} strokeColor={colors.blue500} strokeWidth={1} arrowThickness={7}>
{....}// here i have array of cards
</>
```
![image](https://user-images.githubusercontent.com/37481432/75250409-fbfa5800-57e0-11ea-9995-484b3f9aca1b.png)

**Comment by ilyaburmaka** [comment]
> Hi! Could you provide a minimal reproducing example? 😉

Video or code example?

**Comment by pierpo** [comment]
> > Hi! Could you provide a minimal reproducing example? 😉
> 
> Video or code example?

Code example 😉

**Comment by ilyaburmaka** [comment]
I found an issue in my code. Problem with keys in the map () when I use the index as key - I have this bug if I used id of element for a key - I don't have a bug.
Here you can view example [https://codesandbox.io/embed/bold-golick-35x64?fontsize=14&hidenavigation=1&theme=dark](url)

Good Luck!

**Comment by pierpo** [comment]
Cool, glad that you worked it out 😉
