### ISSUE TITLE
Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by mitchellwarr** [pierpo/react-archer#84]
Every now and then the ArcherContainer fails to unobserve properly. This is happening maybe every third time I render my component

**Comment by pierpo** [comment]
Thank you for the issue. I'll have a look!
An example would be appreciated :blush:

**Comment by mitchellwarr** [comment]
Sorry I cant provide an example for you. Ive since shifted the code away from using this repo and as such have lost the code i used.

What I do know is the code I was using had a lost of useEffects and resizeObservers through it. It is likely do to asynchronous mounting and unmounting issues. Id suggest just making sure promise based code checks to make sure components are actually still mounted before it tries to unobserve. I would have made a pr with some if statements, but I didnt know what react-archer wants to do if the component isnt mounted

**Comment by pierpo** [comment]
Good point, there might be some issues there.
I'll try to reproduce the problem by myself then.

I have a quickfix in mind but I have no way to make sure that it solves the problem yet!

Thank you for the quick answer :wink:
