### ISSUE TITLE
Lines don't draw when scrolling horizontally

### ISSUE THREAD

**Issue by boomgetchopped** [pierpo/react-archer#87]
The library draws lines just fine for on screen parts of the container.

But when I scroll horizontally, I see that nothing is drawn in the area of the screen that was offscreen.

**Comment by pierpo** [comment]
Hello!
Did you solve your problem? Is there an issue with the library or was it a mis-use?
Thanks :wink:

**Comment by boomgetchopped** [comment]
Hi great library.  I was able to fix the issue by manually resizing the svg component that your library creates to match the @scrollwidth value.  By doing that the horizontal scroll works fine.

That might not be the correct solution, but it works for my cases.

**Comment by pierpo** [comment]
Glad to hear that you solved it.

Did you know that there's a non documented "refreshScreen" instance method? You can get it on the ref of the container. You can attach additional listeners to this method if you have troubles with re-rendering.

I should document this.
