### ISSUE TITLE
Arrow heads share the same color

### ISSUE THREAD

**Issue by geoff-va** [pierpo/react-archer#9]
Hi There! Great library - it's become very useful! 

I created two different containers so I could have two different colored arrows, however, it appears the arrow heads share the color of the first one defined. The `strokeColor` seems to properly control the the color of the line, but the arrow heads are the same color.

I did see that individually colored arrows are on the TODO list so I don't know if this is a known issue or not. I noticed that the html `id` field is `arrow` for all arrow head marker objects, so there may a conflict occurring there. 

Thanks!

**Comment by pierpo** [comment]
Hi!

Thanks for your feedback 😊 
Indeed it's something that should have been done a long time ago!

I'll try to work on it asap. This whole TODO has been here for too long 😄 

Cheers!

**Comment by pierpo** [comment]
Just so you know, I first wanted to work on a big refactoring (I am adding Flow types for example). Once the refactoring is done, I'll start working on this 😊

**Comment by geoff-va** [comment]
Cool - thanks for letting me know! Appreciate it!

**Comment by pierpo** [comment]
@geoff-va `0.2.3` should solve it 😊
