### ISSUE TITLE
Problem using CSS grid

### ISSUE THREAD

**Issue by RSchneider94** [pierpo/react-archer#93]
Hello all!

I'm just starting to work with this library and really excited about it! I'm testing it right now and I'm trying to make it work with a Grid CSS Layout. Unfortunately I'm having some trouble here. I uploaded my project at Code Sandbox: https://codesandbox.io/s/4tx93

If you open the screen outside of editor or resizes it, you gonna see what I'm talking about, the arrows seems to be coming from the center of column instead of the elements directly. Another problem that I see, is that the arrows are overlapping each element, going over the elements. If I add `justify-self: center;` to the .col members, it works, but I don't want it actually.

Thanks.

**Comment by pierpo** [comment]
Hey! Thank you for the issue and thank you for the example, this is super helpful!

Your analysis seems correct. I'll try to have a look :blush:

**Comment by pierpo** [comment]
Good news, I solved your main issue with the arrows pointing to the improper element :blush: 
Thank you for the example that allowed me to investigate efficiently!

I'll release a new version that contains the fix.

Can you give it a try?

**Comment by pierpo** [comment]
About your overlapping problem, you can use the (yet) undocumentend `svgContainerStyle` on the `ArcherContainer` to put a -1 z-index :blush: 

This solves your issue:

```jsx
<ArcherContainer className="container" strokeColor="red" svgContainerStyle={{ zIndex: -1 }}>
```

**Comment by RSchneider94** [comment]
hey @pierpo thanks for being so fast! Just updated the package and seems to be working, yes!! But, using your tip with the svgContainerStyle doesn't do the work, unfortunately (see screenshot). The effect I wish is like the documentation examples, where the arrows stop before the elements itself. May I'm doing something wrong?

https://imgur.com/a/N4XQ1WC

Thanks again!

**Comment by pierpo** [comment]
Hi @RSchneider94 !
Sorry I thought you wanted achieve something like this:

![Uploading Screenshot from 2020-04-25 14-07-59.png…]()

In that case you need the zIndex and you need to add a white background color to your elements.

But if I understand correctly, that's what you actually want:

![Screenshot from 2020-04-25 14-09-14](https://user-images.githubusercontent.com/6313316/80279498-61de5f80-86fe-11ea-94d4-aff9b8ff64b9.png)

In that case, you simply have to specify where the arrows start and end :wink: 

```jsx
          <ArcherElement
            id="root"
            relations={[
              {
                targetId: 'element1',
                targetAnchor: 'left',
                sourceAnchor: 'right',
              },
              {
                targetId: 'element2',
                targetAnchor: 'left',
                sourceAnchor: 'right',
              },
              {
                targetId: 'element3',
                targetAnchor: 'left',
                sourceAnchor: 'right',
              },
            ]}
          >
```

**Comment by RSchneider94** [comment]
@pierpo of course, what a dumb question from my side. Of course!! I need to change the start and end. Sorry and thanks for replying! But also thanks for explaining the idea with overlap, in case I really wish to use center. Thanks again for all and have a nice weekend! :smile:

**Comment by pierpo** [comment]
Haha my pleasure :blush: have a nice weekend!
